# Generated by Django 3.0.1 on 2020-04-09 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destLoc', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('adminEmail', models.CharField(max_length=50)),
                ('phpSelection', models.CharField(max_length=10)),
                ('ssl', models.IntegerField()),
                ('state', models.IntegerField(default=1)),
                ('externalApp', models.CharField(default=None, max_length=30)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginSystem.Administrator')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.Package')),
            ],
        ),
        migrations.CreateModel(
            name='GitLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(max_length=5)),
                ('message', models.TextField(max_length=65532)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
        ),
        migrations.CreateModel(
            name='ChildDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(default=None, max_length=200)),
                ('ssl', models.IntegerField()),
                ('phpSelection', models.CharField(default=None, max_length=10)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
        ),
        migrations.CreateModel(
            name='backupSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=15)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.dest')),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
        ),
        migrations.CreateModel(
            name='aliasDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliasDomain', models.CharField(max_length=75)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
        ),
    ]
