# Generated by Django 3.0.1 on 2020-04-09 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=300)),
                ('frequency', models.CharField(max_length=50)),
                ('websiteData', models.IntegerField()),
                ('websiteDatabases', models.IntegerField()),
                ('websiteDataEmails', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
        ),
        migrations.CreateModel(
            name='JobSnapshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('snapshotid', models.CharField(max_length=50)),
                ('destination', models.CharField(default='', max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncBackups.IncJob')),
            ],
        ),
        migrations.CreateModel(
            name='JobSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncBackups.BackupJob')),
            ],
        ),
    ]
